/*  =========================================================================
    azpoller - generated layer of public API

    Copyright (C) 2014 - 2017 Eaton                                        
                                                                           
    This program is free software; you can redistribute it and/or modify   
    it under the terms of the GNU General Public License as published by   
    the Free Software Foundation; either version 2 of the License, or      
    (at your option) any later version.                                    
                                                                           
    This program is distributed in the hope that it will be useful,        
    but WITHOUT ANY WARRANTY; without even the implied warranty of         
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the          
    GNU General Public License for more details.                           
                                                                           
    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.            

################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
    =========================================================================
*/

#ifndef AZPOLLER_LIBRARY_H_INCLUDED
#define AZPOLLER_LIBRARY_H_INCLUDED

//  Set up environment for the application

//  External dependencies
#include <czmq.h>
#include <malamute.h>
#if defined (HAVE_QPID)
#include <stdio.h>
#endif

//  AZPOLLER version macros for compile-time API detection
#define AZPOLLER_VERSION_MAJOR 1
#define AZPOLLER_VERSION_MINOR 0
#define AZPOLLER_VERSION_PATCH 0

#define AZPOLLER_MAKE_VERSION(major, minor, patch) \
    ((major) * 10000 + (minor) * 100 + (patch))
#define AZPOLLER_VERSION \
    AZPOLLER_MAKE_VERSION(AZPOLLER_VERSION_MAJOR, AZPOLLER_VERSION_MINOR, AZPOLLER_VERSION_PATCH)

#if defined (__WINDOWS__)
#   if defined AZPOLLER_STATIC
#       define AZPOLLER_EXPORT
#   elif defined AZPOLLER_INTERNAL_BUILD
#       if defined DLL_EXPORT
#           define AZPOLLER_EXPORT __declspec(dllexport)
#       else
#           define AZPOLLER_EXPORT
#       endif
#   elif defined AZPOLLER_EXPORTS
#       define AZPOLLER_EXPORT __declspec(dllexport)
#   else
#       define AZPOLLER_EXPORT __declspec(dllimport)
#   endif
#   define AZPOLLER_PRIVATE
#else
#   define AZPOLLER_EXPORT
#   if (defined __GNUC__ && __GNUC__ >= 4) || defined __INTEL_COMPILER
#       define AZPOLLER_PRIVATE __attribute__ ((visibility ("hidden")))
#   else
#       define AZPOLLER_PRIVATE
#   endif
#endif

//  Project has no stable classes, so we build the draft API
#undef  AZPOLLER_BUILD_DRAFT_API
#define AZPOLLER_BUILD_DRAFT_API

//  Opaque class structures to allow forward references
//  These classes are stable or legacy and built in all releases


//  Public classes, each with its own header file

#ifdef AZPOLLER_BUILD_DRAFT_API
//  Self test for private classes
AZPOLLER_EXPORT void
    azpoller_private_selftest (bool verbose);
#endif // AZPOLLER_BUILD_DRAFT_API

#endif
/*
################################################################################
#  THIS FILE IS 100% GENERATED BY ZPROJECT; DO NOT EDIT EXCEPT EXPERIMENTALLY  #
#  Read the zproject/README.md for information about making permanent changes. #
################################################################################
*/
